### ISSUE TITLE
pyprophet merge error

### ISSUE THREAD

**Issue by karlssoc** [OpenSWATH/documentation#6]
I have generated osw output files from OpenSwath 2.3 according to http://www.openswath.org/en/latest/docs/openswath_workflow.html. When running pyprophet merge (from https://github.com/grosenberger/pyprophet.git@feature/refactoring) according to
http://www.openswath.org/en/latest/docs/pyprophet.html i get the following error message:

$ pyprophet merge --out=merged.osw TM*.osw
Traceback (most recent call last):
  File "/usr/local/bin/pyprophet", line 9, in <module>
    load_entry_point('pyprophet==2.0.0', 'console_scripts', 'pyprophet')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/main.py", line 201, in merge
    merge_osw(infiles, outfile, subsample_ratio, global_reduce, test)
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/levels_contexts.py", line 137, in merge_osw
    c.execute('DELETE FROM RUN')
sqlite3.OperationalError: no such table: RUN

Thanks,
Christofer

**Comment by grosenberger** [comment]
Hi Christofer,

Thanks for testing the new workflow. Unfortunately the implementation in OpenMS 2.3 is not fully compatible yet with the latest PyProphet version. Could you please try to use OpenMS/develop? Either by building this from scratch or using a recent nightly build. I will update the instructions on the website accordingly to make clear, that full support will only be available in a later OpenMS release version.

**Comment by karlssoc** [comment]
HI,

Thanks for you quick reply and suggestion. I downloaded OpenMS nightly build binary Version: 2.3.0 Jan  4 2018, 01:08:33, Revision: 28bb4f2 and rerun OpenSwathWorkflow and the pyprophet osw merge worked fine.
